export enum SCREENS {
    GLASS = 'GLASS',

    HOME = 'HOME',
    DEVICES = 'DEVICES',
    MAKE_COCKTAIL = 'MAKE_COCKTAIL',

    RECIPES_LIST_ROOT = 'RECIPES_LIST_ROOT',
    RECIPES_LIST = 'RECIPES_LIST',
    RECIPE_DETAILS = 'RECIPE_DETAILS',
    INGREDIENT_DETAILS = 'INGREDIENT_DETAILS',
    CUSTOMIZE_GLASS = 'CUSTOMIZE_GLASS',

    SETTINGS_ROOT = 'SETTINGS_ROOT',
    SETTINGS = 'SETTINGS',

    CUSTOM_RECIPES_ROOT = 'CUSTOM_RECIPES_ROOT',
    RECIPE_EDITOR = 'RECIPE_EDITOR',
}
