export enum SCREENS {
    GLASS = 'GLASS',

    HOME = 'HOME',
    DEVICES = 'DEVICES',
    MAKE_COCKTAIL = 'MAKE_COCKTAIL',
    RECIPES_LIST = 'RECIPES_LIST',
    RECIPE_DETAILS = 'RECIPE_DETAILS',
    INGREDIENT_DETAILS = 'INGREDIENT_DETAILS',
    CUSTOMIZE_GLASS = 'CUSTOMIZE_GLASS',

    SETTINGS = 'SETTINGS',
}
