export enum SCREENS {
    HOME = "HOME",
    SCAN_DEVICES = "SCAN_DEVICES",
    MAKE_COCKTAIL = "MAKE_COCKTAIL",
    RECIPES_LIST = "RECIPES_LIST",
    RECIPE_DETAILS = "RECIPE_DETAILS",
    INGREDIENT_DETAILS = "INGREDIENT_DETAILS",
}
